# Generated by Django 2.2.12 on 2021-08-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("browser", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="taxonomicunit",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="browser.TaxonomicUnit",
            ),
        )
    ]
