# Generated by Django 3.2.5 on 2021-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("browser", "0003_auto_20210808_1426")]

    operations = [
        migrations.AlterField(
            model_name="specificgene",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="taxonomicunit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
