# Generated by Django 3.2.2 on 2021-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("browser", "0008_auto_20211002_1224")]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="taxonomic_unit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Domain"),
                    (1, "Phylum"),
                    (2, "Class"),
                    (3, "Order"),
                    (4, "Family"),
                    (5, "Genus"),
                    (6, "Species"),
                ],
            ),
        ),
        migrations.DeleteModel(name="TaxonomicUnit"),
    ]
