# Generated by Django 3.2.5 on 2021-11-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('browser', '0011_auto_20211031_1743'), ('browser', '0012_alter_taxon_name'), ('browser', '0013_auto_20211031_1845'), ('browser', '0014_alter_lineage_species')]

    dependencies = [
        ('browser', '0010_rename_protein_number_taxon_protein_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='parent',
        ),
        migrations.AlterField(
            model_name='taxon',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='browser.taxon')),
                ('genus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genus', to='browser.taxon')),
                ('klass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='browser.taxon')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='browser.taxon')),
                ('phylum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phylum', to='browser.taxon')),
                ('species', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='browser.taxon')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='browser.taxon')),
            ],
        ),
    ]
