# Generated by Django 3.2.5 on 2021-11-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0011_auto_20211031_1743_squashed_0014_alter_lineage_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineage',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='browser.taxon'),
        ),
    ]
