# Generated by Django 3.2.5 on 2021-11-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0012_alter_lineage_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_species', to='browser.taxon'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g_species', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_domain', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_family', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_genus', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_klass', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_order', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='phylum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_phylum', to='browser.taxon'),
        ),
        migrations.AlterField(
            model_name='lineage',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineages_species', to='browser.taxon'),
        ),
    ]
